### ISSUE TITLE
Task 5.3 | Was genau ist mit "characters" gemeint?

### ISSUE THREAD

**Issue by okubon** [dis-data-modeling-2020/slides#4]
Die letzten beiden Aufgaben von Task 5.3 lauten: 

> What are the top 5 characters in the char column?
> What are the top 5 characters in the dialogs?

Da wir es ja mit einem Film zu tun haben, bin ich davon ausgegangen, dass mit "characters" die Namen der Figuren im Film gemeint sind, wie Frodo oder Sam. 

Ich möchte nur sicher gehen, dass nicht damit die Buchstaben in den Wörtern gemeint sind.

**Comment by phschaer** [comment]
... Es geht um die Personen/Figuren, nicht die einzelnen Zeichen. :-)
